MClub/Models/Reserve.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MClub.Models
{
    public class Reserve
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public int Persons { get; set; }
        public DateTime From { get; set; }
        public DateTime To { get; set; }
        public string Comment { get; set; }
        public ApplicationUser User { get; set; }
        public string UserId { get; set; }
        public Room Room { get; set; }
        public int RoomId { get; set; }
    }
}

MClub/Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MClub.Models
{
    public class Room
    {
        public Room()
        {
            Images = new List<Image>();
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int? MaxPersons { get; set; }
        public string Description { get; set; }
        public bool IsRecived { get; set; }
        public DateTime? ReservationDate { get; set; }
        public ICollection<Image> Images { get; set; }
    }
}

MClub/Models/ViewModels/ReserveViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MClub.Models.ViewModels
{
    public class ReserveViewModel
    {
        [Display(Name = "Введите ваше имя и фамилию")]
        [Required]
        public string Name { get; set; }
        [Display(Name = "Выберите дату вашего приезда")]
        [Required]
        public DateTime From { get; set; }
        [Display(Name = "Количество дней проживания")]
        public int To { get; set; }
        [Display(Name = "Комментарий к бронированию")]
        public string Comment { get; set; }
        public Room Room { get; set; }
        [Display(Name = "Введите количество человек")]
        public int Persons { get; set; }
    }
}

MClub/Controllers/RoomController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using MClub.Data;
using MClub.Models;
using MClub.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MClub.Controllers
{
    [Authorize]
    public class RoomController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _manager;
        private Task<ApplicationUser> GetCurrentUserAsync() => _manager.GetUserAsync(HttpContext.User);
        public RoomController(ApplicationDbContext context, UserManager<ApplicationUser> manager)
        {
            _context = context;
            _manager = manager;
        } 
        
        public IActionResult Index() => View(_context.Rooms.Include(p=>p.Images).ToList());

        [HttpGet]
        public IActionResult Reserve(int id)
        {
            Room room = _context.Rooms.FirstOrDefault(x => x.Id == id);

            ReserveViewModel model = new ReserveViewModel()
            {
                From = DateTime.Now.AddDays(1),
                Room = room
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Reserve(ReserveViewModel model, int id)
        {
            if (ModelState.IsValid)
            {
                Reserve reserve = new Reserve()
                {
                    Comment = model.Comment,
                    From = model.From,
                    To = model.From.AddDays(model.To),
                    Name = model.Name,
                    Persons = model.Persons,
                    Room = _context.Rooms.FirstOrDefault(x => x.Id == id),
                    User = await GetCurrentUserAsync()
                };

                reserve.Room.IsRecived = true;
                _context.Rooms.Update(reserve.Room);
                _context.Reserves.Add(reserve);
                _context.SaveChanges();
                return View("ThankYou");
            }
            return View(model);
        }

        public IActionResult Rooms(int id = 0)
        {
            if (id == 0)
            {
                id = _context.Rooms.FirstOrDefault().Id;
            }

            return View(_context.Rooms.Where(x => x.Id == id).Include(x => x.Images).FirstOrDefault());
        }
    }
}

MClub/Views/Room/Index.cshtml
@model IEnumerable<Room>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Размещение</h2>

<div>
@foreach (var room in Model)
{
    <div class="col-md-12 block-style">
    <div class="col-md-2">
        @if (room.Images.Any())
        {<div class="col-md-12"><a href="@room.Images.FirstOrDefault().VirtualPath" class="lightbox"><img src="@room.Images.FirstOrDefault().VirtualPath" width="150" /></a></div>}    
    </div>
        <div class="col-md-10">
            <div class="col-md-3 persons">@room.Name</div>
            <div class="col-md-3 persons">Вместимость: @room.MaxPersons чел.</div>
            <div class="col-md-3 persons">Цена сутки: @room.Price руб.</div>
            @if (room.IsRecived)
            {
                <div class="col-md-3 text-danger">ЗАНЯТО</div>
            }
            else
            {
                <div class="col-md-3 text-primary">СВОБОДНО</div>
            }

        </div>
        <div class="col-md-10">
            <div class="col-md-6">Описание: @Html.Raw(room.Description)</div>   
            <div class="col-md-3"><a asp-controller="Room" asp-action="Rooms" asp-route-id="@room.Id" class="text-warning">Подробнее</a></div>
            @if (!room.IsRecived)
            {
                <div class="col-md-3"><a asp-controller="Room" asp-action="Reserve" asp-route-id="@room.Id" class="text-danger">ЗАБРОНИРОВАТЬ</a></div>
            }
            
        </div>
    </div>
}       
</div>

MClub/Views/Room/Reserve.cshtml
@model ReserveViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Звбронировать Номер</h2>

<form asp-action="Reserve" asp-route-id="@Model.Room.Id" class="form-horizontal" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Name" type="text" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Persons" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Persons" type="number" />
            <span asp-validation-for="Persons" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="From" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="From" type="date" />
            <span asp-validation-for="From" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="To" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="To" type="number" />
            <span asp-validation-for="To" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Comment" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <textarea  asp-for="Comment" type="text" rows="10" cols="45"></textarea>
            <span asp-validation-for="Comment" class="text-danger"></span>
        </div>
    </div>
    
    <div class="form-group col-md-4">
        <button type="submit">Забронировать</button>
    </div>
</form>

MClub/Views/Room/Rooms.cshtml
@model Room

@{
    ViewBag.Title = @Model.Name;
    Layout = "_Layout";
}



<div class="article-title col-md-12">
    @Model.Name
</div>

<div class="col-md-12">
    @if (Model.Images.Any())
    {
        <div class="article-img">
            <a href="@Model.Images.FirstOrDefault().VirtualPath" class="lightbox"><img src="@Model.Images.FirstOrDefault().VirtualPath" width="150"/></a>
        </div>
    }
    <div class="col-md-5 text-info">Вместимость</div>
    <div class="persons col-md-5">
        @(Model.MaxPersons < 5 ? Model.MaxPersons + " Человека" : Model.MaxPersons + " Человек")
    </div>
    <div class="col-md-5 text-info">Стоимость в сутки</div>
    <div class="persons col-md-5">
        @Model.Price Руб.
    </div>
</div>
<div class="col-md-12">
        @Html.Raw(Model.Description)
</div>
@if(!@Model.IsRecived) 
{
    <div class="col-md-4"><a asp-controller="Room" asp-action="Reserve" asp-route-id="@Model.Id" class="btn-danger ">ЗАБРОНИРОВАТЬ</a></div> 
}
else
{
    <div class="col-md-4 text-warning">НОМЕР УЖЕ ЗАБРОНИРОВАН</div> 
}
        <div class="col-md-12">
            @if (Model.Images.Count > 1)
            {
                foreach (var img in Model.Images.ToList())
                {
                    <div class="col-md-4">
                        <a href="@img.VirtualPath" class="lightbox"><img src="@img.VirtualPath" width="300" /></a>
                    </div>
                }
            }
        </div>

MClub/Views/Room/ThankYou.cshtml
@{
    ViewBag.Title = "Спасибо";
    Layout = "_Layout";
}

Спасибо, ваш номер забронирован